<script>
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_statistiques').toggle(true);
$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.PNG';?>'  /> Statistiques </span></a></li>");
dep_menu_statistiques1();
$('#menu_statistiques_style').css({'font-weight':'bold','color':'white','font-size':'21px'});
</script>
<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/jquery-ui.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/maternite/accouchement/styleAdmission.css');?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jqueryCharts/jquery.canvasjs.min.js');?>

<?php use Maternite\View\Helpers\DateHelper;
$Control = new DateHelper();
$today = new \DateTime ( 'now' );
//var_dump($today);exit();
?>

<?php
$form = $this->form;
$form->setName ( 'AVIS' );
$form->setAttribute ( 'action', $this->url ( 'accouchement', array (
		'action' => 'info-statistique' 
) ) );
$form->setAttribute ( 'target', '_blank' );
$form->setAttribute ( 'method', 'post' );
$form->prepare ();
echo $this->form ()->openTag ( $form );
?>




<style>
#contenuInterface{ visibility: hidden; }
#date_stat{
  border-bottom-left-radius: 5px; 
  border-bottom-right-radius: 5px;
	 border-top-left-radius: 5px; 
	 background-color: #eefeee;
	  border-top-right-radius: 5px;
	   width: 10%; /* la largeur du champ input*/
}

#thoughtbot button
{
    width:auto;
    padding:8px 0;
    text-align:center;
    display: inline-block;
    float:left;
    margin:0 8px 0 0;
    border-radius:7px;
    font-size: 0.85em;
	font-weight: bold;
    width:80px;
    color:#000;
    font-family: Arial,sans-serif;
	box-shadow: 0 0 1px rgba( 0, 0, 0, 0.2), 0 -1px 0 rgba( 255, 255, 255, 0.1);
    text-shadow: 0px 1px 0px rgba( 255, 255, 255, 0.3);
}

</style>
<script type="text/javascript">
$(function() {
    $('#date_stat').datepicker( {
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        dateFormat: 'MM yy',
        onClose: function(dateText, inst) {
            $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
        }
    });
});
</script>
<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
	 
});
</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span >  Veuillez selectionner une p&eacute;riode</span>   <?php echo $this->formRow($form->get('date_stat'));?>
  <button id="thoughtbot" name="terminer" style=" height:35px; ">Ok</button>
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenuInterface" >
<div id="contenu" >

    
    <div style="float:center;">
  
    </div>
	<div style="width: 100%;  ">
	
	
</div>
	
	
	
	
	
	         <?php echo $this->form()->closeTag(); ?>

</div>
</div>